#### EVALUACIÓN NUMPY NATALIA BARQUÍN

1. Importa la librería de NumPy.

In [1]:
import numpy as np

2. Crea un array de 1 dimensión y 10 elementos.

In [2]:
array_uni = np.random.randint(1,100, (10))
array_uni

array([42, 54,  7, 80, 79, 52, 37, 72, 57, 33])

3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [12]:
def par_impar(array):
    '''
    Crea un array de str vacío igual al array que recibe como parámetro, y le añade
    valor 'par' o 'impar' en función de cómo sea ese valor en el array original.
    Parámetro: array que queramos modificar (array de ints o floats)
    Return: array de str con valores 'par' o 'impar'
    '''

    array_pares_impares = np.empty_like(array, dtype = np.dtype('U100'))

    for i in range(array.size):
        if array[i] %2 == 0:
            array_pares_impares[i] = "par"
        else:
            array_pares_impares[i] = "impar"

    return array_pares_impares

In [13]:
array_par_impar = par_impar(array_uni)
array_par_impar

array(['par', 'par', 'impar', 'par', 'impar', 'par', 'impar', 'par',
       'impar', 'impar'], dtype='<U100')

4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [6]:
array_bi = np.reshape(array_par_impar,(2,5))
array_bi

array([['par', 'par', 'impar', 'par', 'impar'],
       ['par', 'impar', 'par', 'impar', 'impar']], dtype='<U100')

5. Extrae los elementos comunes de los siguientes arrays.

In [7]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
np.intersect1d(array1, array2)

array([2, 4])

6. Extraed los elementos que están en el array1 pero no en el array2.

In [9]:
np.setdiff1d(array1, array2)

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

In [45]:
np.where(array1 == array2)

(array([1, 3, 5, 7]),)

8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [25]:
array_50 = np.random.randint(1,50, (3,5))
array_50

array([[13, 23,  8, 36, 49],
       [24, 29, 27, 18, 46],
       [34, 38, 36, 16,  1]])

In [35]:
condicion1 = array_50 > 40
condicion2 = array_50 < 10

array_50[condicion1 | condicion2]

array([ 8, 49, 46,  1])

9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [38]:
array_floats = np.random.uniform(5,10, (5,3)).round(2)
array_floats

array([[8.15, 7.99, 9.01],
       [5.18, 6.84, 5.23],
       [8.38, 7.67, 5.35],
       [8.46, 5.21, 6.07],
       [5.71, 9.66, 6.09]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20.
- Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas


In [39]:
array_tri = np.random.randint(1,20, (2,4,7))
array_tri

array([[[ 4,  3,  5,  8, 10,  3,  9],
        [18, 19,  9, 13,  3,  8,  5],
        [ 4,  7, 15,  2, 14,  1, 13],
        [ 7,  4,  6,  1,  5, 12, 13]],

       [[18, 18, 13,  9, 19,  4, 11],
        [16, 11, 19, 13,  8, 14, 18],
        [ 6,  5,  8,  3,  7,  3,  3],
        [ 9, 15, 14,  7,  2, 15,  9]]])

In [41]:
#modificamos según las posiciones de las matrices, filas y columnas originales.
np.transpose(array_tri, (1,2,0))

array([[[ 4, 18],
        [ 3, 18],
        [ 5, 13],
        [ 8,  9],
        [10, 19],
        [ 3,  4],
        [ 9, 11]],

       [[18, 16],
        [19, 11],
        [ 9, 19],
        [13, 13],
        [ 3,  8],
        [ 8, 14],
        [ 5, 18]],

       [[ 4,  6],
        [ 7,  5],
        [15,  8],
        [ 2,  3],
        [14,  7],
        [ 1,  3],
        [13,  3]],

       [[ 7,  9],
        [ 4, 15],
        [ 6, 14],
        [ 1,  7],
        [ 5,  2],
        [12, 15],
        [13,  9]]])